runner:
  cpplint:
    cmd: cpplint --linelength=160 --filter="-legal/copyright,-whitespace/braces,-whitespace/indent,-whitespace/newline,-build/c++11,-build/include_directory,-build/include" BizTelework/* BizTeleworkUpdater/* BizTeleworkHook/* Library/* 2>&1
    errorformat:
      - "%f:%l: %m"
    level: warning
