#pragma once

#include <Windows.h>

enum
{
    BIZ_TELEWORK_MESSAGE_KEYBOARD = WM_APP,
    BIZ_TELEWORK_MESSAGE_MOUSE,
    BIZ_TELEWORK_MESSAGE_NOTIFY_ICON,
    BIZ_TELEWORK_MESSAGE_WORK_LOGS_RESPONSE,
    BIZ_TELEWORK_MESSAGE_USER_CONDITION_LOGS_RESPONSIVE,
    BIZ_TELEWORK_MESSAGE_DAY_OFF_REQUESTS_RESPONSIVE,
    BIZ_TELEWORK_MESSAGE_AUTHENTICATE_RESPONSIVE,
    BIZ_TELEWORK_MESSAGE_KEYBOAD_AND_MOUSE_HOOK,
    BIZ_TELEWORK_MESSAGE_ON_DUTY_DIALOG_REMIND_TIMER,
    BIZ_TELEWORK_MESSAGE_CONTEXT_MENU,
    BIZ_TELEWORK_MESSAGE_REGISTER_SESSION_NOTIFICATION,
    BIZ_TELEWORK_MESSAGE_SET_SHOWING_ON_DUTY_DIALOG_REMIND_TIMER,
    BIZ_TELEWORK_MESSAGE_TOAST_NOTIFICATION_HANDLER,
    BIZ_TELEWORK_MESSAGE_WORK_TARGET,
};
