//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ で生成されたインクルード ファイル。
// BizTelework.rc で使用
//
#define IDD_BIZTELEWORK_HEALTH_STATUS_DIALOG 102
#define IDR_MAINFRAME                   128
#define IDB_STATIC_IMAGE                129
#define IDD_BIZTELEWORK_DAY_OFF_VERIFICATION_DIALOG 132
#define IDD_BIZTELEWORK_ON_DUTY_DIALOG  134
#define IDD_BIZTELEWORK_OFF_DUTY_DIALOG 136
#define IDD_BIZTELEWORK_FAILED_CALL_API_DIALOG 138
#define IDD_BIZTELEWORK_AUTHENTICATION_DIALOG 140
#define IDD_BIZTELEWORK_WORK_DAY_TARGET_DIALOG 142
#define IDC_BUTTON_GOOD_HEALTH          1000
#define IDC_BUTTON_NORMAL_HEALTH        1001
#define IDC_STATIC_FEELING_QUESTION     1002
#define IDC_STATIC_ERROR_LABEL          1003
#define IDC_STATIC_TAKE_BREAK_QUESTION  1004
#define IDC_BUTTON_START                1005
#define IDC_BUTTON_NOT_YET              1006
#define IDC_STATIC_NOTIFICATION         1007
#define IDC_BUTTON_END_WORK             1008
#define IDC_STATIC_TEXT_FAILED_CALL_API 1009
#define IDC_BUTTON_RETURN_FAILED_CALL_API 1010
#define IDC_STATIC_OPERATING_TIME_LABEL 1011
#define IDC_STATIC_OPERATING_TIME_CONTENT 1012
#define IDC_BUTTON_BAD_HEALTH           1013
#define IDC_BUTTON_OFF_DAY              1014
#define IDC_BUTTON_DO_WORKING           1015
#define IDC_EDIT_COMPANY_CODE           1016
#define IDC_EDIT_ACTIVE_CODE            1017
#define IDC_STATIC_TEXT_ENTER_URL       1018
#define IDC_EDIT_ENTER_UPDATE_URL       1019
#define IDC_BUTTON_LOGIN                1020
#define IDC_STATIC_ACTIVE_ERROR         1021
#define IDB_EXPAND_MORE_IMAGE           1022
#define IDB_EXPAND_LESS_IMAGE           1023
#define IDC_STATIC_EXPLANATION          1024
#define IDB_CLOSE_IMAGE                 1025
#define IDC_STATIC_AUTH_SUCCESS         1026
#define IDC_STATIC_DO_WHAT_TODAY        1027
#define IDC_EDIT_WORK_DAY_TARGET        1028
#define IDC_BUTTON_TARGET_START         1029

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        144
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1030
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
