#pragma once
#ifndef _WORKERTHREAD_H_
#define _WORKERTHREAD_H_

enum WTSTAT {
    WTSTAT_NONE,
    WTSTAT_RUNNING,
    WTSTAT_RUN,
    WTSTAT_RUN_WAITING,
    WTSTAT_STOPPING,
    WTSTAT_STOP,
};

#endif //_WORKERTHREAD_H_
