import "oaidl.idl";
[
    uuid(4012BC9F-1554-4649-B3DE-8450128D4CED),
    version(1.0)
]
interface BizTeleworkUpdaterRpc
{
    /*
     * @return
     *  S_OK indicates that you need fetch from URL.
     *  ERROR_EMPTY indicates no need to fetch from URL.
     *  Other value idicates failed to call this function.
     */
    HRESULT BizTeleworkUpdaterRpc_PollFetchingTask([in, out, string, size_is(UrlLen)] wchar_t Url[], [in] unsigned int UrlLen,
                                                   [in, out, string, size_is(DstFilePathLen)] wchar_t DstFilePath[], [in] unsigned int DstFilePathLen);

    void BizTeleworkUpdaterRpc_PushFetchingResult([in] boolean succeeded);
}
